### ISSUE TITLE
Sidebar - Resolution Checking: please position the form below the content in 991 and below resolution

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/Hollywood-Kitchens#66]
![image](https://cloud.githubusercontent.com/assets/17717843/16575647/74ea2a58-42bc-11e6-9b1d-c2c1fe4daf35.png)

**Comment by euveng** [comment]
Is this still valid now?

**Comment by roseliesromeo** [comment]
Yes, display form at the bottom from iPad resolution (768) - 991.

**Comment by euveng** [comment]
I have to disagree with this issue. In another build, I was requested to keep the form in the sidebar between 768 - 991px. We need to be consistent.

Please refer to https://github.com/TitanDigital/Boeing-Plumbing/issues/74

**Comment by roseliesromeo** [comment]
Yes, we should be consistent.  But it turns out you have different implementation for each site as well and how we have to adjust.
See how the forms look on each site. And notice the left and right padding. Either display the form at the bottom for this site or adjust the padding whichever is easier because it doesn't look good.
![image](https://cloud.githubusercontent.com/assets/11186313/17281739/941e4eee-57d0-11e6-9655-21302644196e.png)

**Comment by euveng** [comment]
Fixed for all pages

**Comment by roseliesromeo** [comment]
No change made.

**Comment by euveng** [comment]
Sorry, should this apply to all pages with the sidebar?

**Comment by roseliesromeo** [comment]
Yes please, make it consistent throughout the site. This has been applied in the gallery single and not in the gallery main page.

**Comment by euveng** [comment]
Fixed.
